### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Systemad** [DirtyUnicorns/android_device_lge_bullhead#1]

**Comment by Mazda--** [comment]
Go to our G+ community if you want support.

**Comment by Systemad** [comment]
@Mazda--
I did, but after 3 days with no response I went here because I'm not really sure where to post.
https://plus.google.com/101201397987030621341/posts/3aJuvQboCRJ
Anyway, I think I solved it, will try to compile tomorrow. 

Thanks

**Comment by Mazda--** [comment]
Ok

**Comment by nychitman1** [comment]
I will look into this and fix, if necessary.
